### ISSUE TITLE
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js

### ISSUE THREAD

**Issue by titov-andrei** [rolling-scopes/rsschool-app#513]
```
> server@1.0.0 start /home/andrew/CODE/JS/React/rsschool-app/server
> tsnd --ignore-watch node_modules --inspect --notify false -r dotenv/config -r tsconfig-paths/register -- ./index.ts | pino-pretty -i time,hostname,pid,host,method,remoteAddress

Ignore watch: [ 'node_modules' ]
Using ts-node version 8.6.2, typescript version 4.0.2
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at Object.watch (fs.js:1470:11)
    at add (/home/andrew/CODE/JS/React/rsschool-app/server/node_modules/filewatcher/index.js:74:34)
    at /home/andrew/CODE/JS/React/rsschool-app/server/node_modules/filewatcher/index.js:93:5
    at FSReqCallback.oncomplete (fs.js:177:5)
Debugger listening on ws://127.0.0.1:9229/51fbd3ab-8bcc-4166-8ed2-4b59ac19bd94
For help, see: https://nodejs.org/en/docs/inspector
Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

```

**Comment by apalchys** [comment]
@titov-andrei  it seems you use NodeJS 14.  Unfortunately, we support only NodeJS 12 (LTS version)
